services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: dsikorski
      POSTGRES_PASSWORD: dsikorski
      POSTGRES_DB: book
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres:
