services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: dsikorski
      POSTGRES_PASSWORD: dsikorski
      POSTGRES_DB: book
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
  postgres_test:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: dsikorski
      POSTGRES_PASSWORD: dsikorski
      POSTGRES_DB: book_test
    ports:
      - '5432:5432'
    volumes:
      - data2:/var/lib/postgresql/data
volumes:
  data:
  data2:
